# Generated by Django 6.0.7 on 2026-08-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_producto_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
    ]
